### ISSUE TITLE
Non preemptive proxy auth is broken over HTTPS (1.9 only)

### ISSUE THREAD

**Issue by IskanderMustafin** [AsyncHttpClient/async-http-client#1054]
Hello, I have a problem with using proxy servers in 1.9.x branch of AsyncHttpClient.

I'm setting proxy server, and it works OK with HTTP protocol, but when I'm requesting HTTPS pages proxy isn't used (it uses my local IP, not proxy IP address). 

This is example code I'm using:  

```
private AsyncHttpClientConfig cfg = new AsyncHttpClientConfig.Builder( ).
                setConnectTimeout( 20000 ).
                setRequestTimeout( 20000 ).
                setWebSocketTimeout(20000).
                setMaxRequestRetry(3).
                setReadTimeout( 20000 ).
                setAcceptAnyCertificate( true ).
                build( )

   private AsyncHttpClient  client = new AsyncHttpClient( cfg )


  client.prepareGet( url ).
                 setProxyServer( new ProxyServer( ProxyServer.Protocol.HTTP, "myproxyurl", 2222, "principal", "password" ) ).
                 execute( ).
                 get()
```

**Comment by slandelle** [comment]
AHC 1.9 ProxyServer API is a non sense, where [ProxyServer.Protocol](https://github.com/AsyncHttpClient/async-http-client/blob/1.9.x/src/main/java/com/ning/http/client/ProxyServer.java#L34) mixes proxy types (HTTP, SOCKS is not supported), auth schemes (NTLM, KERBEROS, SPNEGO, where are BASIC and DIGEST?) and HTTPS (because you might want different proxies/ports for HTTP and HTTPS).

API is fixed in AHC2.

In AHC1, you have to set to HTTPS when performing a request over HTTPS.

**Comment by IskanderMustafin** [comment]
Thanks you for reply, I tried your suggestion to use `ProxyServer.Protocol.HTTPS` when performing HTTPS requests: 

     val protocol = if (url.toLowerCase.startsWith("https"))  ProxyServer.Protocol.HTTPS else ProxyServer.Protocol.HTTP


and then in code 

    setProxyServer( new ProxyServer( protocol, "myproxyurl", 2222, "principal", "password" ) ).


But problem isn't resolved. It still doesn't use proxy server for HTTPS requests. 

Any ideas? 

Thanks

**Comment by slandelle** [comment]
Which version of AHC do you use exactly?

**Comment by IskanderMustafin** [comment]
This is piece of pom.xml:

     
      <dependency>
            <groupId>com.ning</groupId>
            <artifactId>async-http-client</artifactId>
            <version>1.9.27</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty</artifactId>
            <version>3.10.0.Final</version>
        </dependency>

**Comment by slandelle** [comment]
What's the issue exactly? Is the proxy ignored, or is the issue with the proxy auth? Can you provide logs?

**Comment by IskanderMustafin** [comment]
Seems you are right, there problem with auth. I added logging for `com.ning.http.client`, and seems AHC first tries to make request via proxy (using CONNECT method), and if proxy fails (it returns 407 error) then AHC trying to  make request without proxy server  (using GET method). 

I'm not sure why proxy returns 407 error when using HTTPS

I'm attaching logs below.

It would be nice if you help me to understand how to fix it. 

Thanks  

```
20:45:47,233 DEBUG NettyConnectListener:68 - Using non-cached Channel [id: 0x833a0a77, /192.168.0.102:32348 => zproxy.luminati.io/104.131.148.183:22225] for CONNECT 't.mobitrk.com:443'
20:45:47,474 DEBUG HttpProtocol:409 - 

Request DefaultHttpRequest(chunked: false)
CONNECT t.mobitrk.com:443 HTTP/1.1
Connection: keep-alive
Host: t.mobitrk.com
Accept: */*
User-Agent: AHC/1.0

Response DefaultHttpResponse(chunked: true)
HTTP/1.1 407 Proxy Authentication Required
Proxy-Authenticate: Basic realm="Luminati"
Proxy-Connection: close

20:45:47,475 DEBUG HttpProtocol:289 - Sending proxy authentication to https://t.mobitrk.com/?a=t&aff_id=3&o_id=4690&sub_id=&ios_ifa=&google_aid=&windows_aid=
20:45:47,477 DEBUG HttpProtocol:320 - Sending proxy authentication to https://t.mobitrk.com/?a=t&aff_id=3&o_id=4690&sub_id=&ios_ifa=&google_aid=&windows_aid=
20:45:47,477 DEBUG ChannelManager:367 - Closing Channel [id: 0x833a0a77, /192.168.0.102:32348 => zproxy.luminati.io/104.131.148.183:22225] 
20:45:47,478 DEBUG Processor:113 - Channel Closed: [id: 0x833a0a77, /192.168.0.102:32348 :> zproxy.luminati.io/104.131.148.183:22225] with attribute INSTANCE
20:45:48,259 DEBUG NettyConnectListener:68 - Using non-cached Channel [id: 0x93c66593, /192.168.0.102:32349 => t.mobitrk.com/54.235.202.140:443] for GET '/?a=t&aff_id=3&o_id=4690&sub_id=&ios_ifa=&google_aid=&windows_aid='
20:45:48,455 DEBUG HttpProtocol:409 - 

Request DefaultHttpRequest(chunked: false)
GET /?a=t&aff_id=3&o_id=4690&sub_id=&ios_ifa=&google_aid=&windows_aid= HTTP/1.1
Cookie: 
User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; SM-G920F Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile
Connection: keep-alive
Host: t.mobitrk.com
Proxy-Authorization: Basic bHVtLWN1c3RvbWVyLWNsaWNrc21CHANGEDlbi1jb3VudHJ5LURFOmNjMjfhjZjViMmJiMA==
Accept: */*

Response DefaultHttpResponse(chunked: false)
HTTP/1.1 200 OK
Date: Wed, 16 Dec 2015 15:45:49 GMT
Server: nginx/1.8.0
Content-Length: 319
Connection: keep-alive
```

**Comment by slandelle** [comment]
That's indeed a bug. I'm pretty sure that AHC2.0.0-RC3 works fine.

As a workaround, you could enable preemptive auth.

As there's a workaround and AHC2 works fine, I don't think I'll personally spend time trying to fix it.

I'll leave this open if anyone's willing to contribute.

**Comment by IskanderMustafin** [comment]
Thanks. I think I'll use AHC2. But I couldn't yet find any documentation/migration guide for second version. Is there some docs?

**Comment by slandelle** [comment]
No, AHC 2 is still undocumented (in Release Candidate phase).

**Comment by simao** [comment]
Hi,

I am having the same problem. Tried to use preemptive auth but still having the same issue. Is there any other workaround?

I am using preemptive auth overriding the realmBuilder method in ProxyServer, is there another way?

**Comment by slandelle** [comment]
See above comment: https://github.com/AsyncHttpClient/async-http-client/issues/1054#issuecomment-165277419

**Comment by simao** [comment]
Yes, the title says it doesn't work for non preemptive auth, so I thought it could work for preemptive auth. Is that not the case? 

Thanks.

**Comment by slandelle** [comment]
It should.

**Comment by simao** [comment]
ok, so preemptive auth should be enabled like that? override that method and setUsePreemptive?

**Comment by ialekseev** [comment]
Hi guys, I also would appreciate an example of configuring proxy with auth using mentioned workaround. Can't make it work either. Thank you.

**Comment by IskanderMustafin** [comment]
I fixed it using primitive auth as `slandelle` mentioned. This is my code (Scala): 

```
    def doEnhancedRequest( url: String, userAgent: String, cookiesHeader: Option[String], proxyCountryCode: String): WebClient.ResponseDetails = {

      val protocol = if (url.toLowerCase.startsWith("https"))  ProxyServer.Protocol.HTTPS else ProxyServer.Protocol.HTTP

      val proxy = new ProxyServer( protocol, "yourproxyaddress", 22225, s"yourlogin-$proxyCountryCode", "yourpassword" )

      // need to use primitive auth because bug in AHC library: https://github.com/AsyncHttpClient/async-http-client/issues/1054
      val realm = proxy.realmBuilder().setUsePreemptiveAuth(true).build()

      val requestBuilder = client.prepareGet(url)

      requestBuilder.setRealm(realm)

      val response = requestBuilder.
                     addHeader( "Cookie", cookiesHeader.getOrElse( "" ) ).
                     addHeader("User-Agent", userAgent ).
                     setProxyServer( proxy ).
                     execute( ).
                     get()

      //log.debug("Response: " + response.getStatusCode + response.getStatusText + response.getResponseBody)
      val cookies = Option( response.getHeader( "Set-Cookie" ) )

      WebClient.ResponseDetails(url, getRedirectUrl(response), cookies, response.getStatusCode)

   }

```

**Comment by ialekseev** [comment]
@IskanderMustafin, thanks a lot!

**Comment by slandelle** [comment]
Duplicate of #1152, closed by #1158
